<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText UFT One" productVer="24.2" os="Windows 11" host="IBM-68H9R24"><DocLocation><![CDATA[C:\Users\BanuchandhiranM\Downloads\POSRegression_Latest (2)\POS_PatchValidation]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText UFT One"  >
<DName><![CDATA[POS_PatchValidation]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
UIA.]]></Details>
<Time><![CDATA[12-06-2026 - 09:29:26]]></Time>
<TimeTick>1781236766</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[General run error.<BR/>Line (19): &quot;WshShell.Run _&quot;. ]]></Details>
<Time><![CDATA[12-06-2026 - 09:29:34]]></Time>
<TimeTick>1781236774</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Failed" Source="Action1" SourceLine="18" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[AIUtil.SetContext]]></Obj>
<Details plainTxt="False" ><![CDATA[Set context Window("[ IBM Endpoint Manager for Remote Control ]") for AIUtil]]></Details>
<Time><![CDATA[12-06-2026 - 09:29:51]]></Time>
<TimeTick>1781236791</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="10" nType="AIUtil" Source="Action1" SourceLine="25" >
<Disp><![CDATA[AIUtil.SetContext]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Login Loaded]]></Obj>
<Details ><![CDATA[US90L01-09956]]></Details>
<Time><![CDATA[12-06-2026 - 09:29:54]]></Time>
<TimeTick>1781236794</TimeTick>
<NodeArgs eType="User" icon="6" nRep="11" Source="Action1" SourceLine="130" >
<Disp><![CDATA[Login Loaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:16]]></Time>
<TimeTick>1781236816</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" status="Warning" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"AIUtil("down_triangle",&nbsp;micAnyText,&nbsp;micFromTop,&nbsp;1)".<br/>]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:16]]></Time>
<TimeTick>1781236816</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>locator_data = 1<br>locator = FromTop<br>control_class = down_triangle<br>]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:16]]></Time>
<TimeTick>1781236816</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" status="Warning" nType="Description" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="15" status="Warning" nType="Run Error" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;AIUtil(&quot;down_triangle&quot;, micAnyText, micFromTop, 1)&quot;.<BR/><BR/>Line (146): &quot;AIUtil( _&quot;. ]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:16]]></Time>
<TimeTick>1781236816</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" status="Failed" Source="Action1" SourceLine="145" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:48]]></Time>
<TimeTick>1781236848</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" status="Warning" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"AIUtil("down_triangle",&nbsp;micAnyText,&nbsp;micFromTop,&nbsp;1)".<br/>]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:48]]></Time>
<TimeTick>1781236848</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>locator_data = 1<br>locator = FromTop<br>control_class = down_triangle<br>]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:48]]></Time>
<TimeTick>1781236848</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" status="Warning" nType="Description" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="21" status="Warning" nType="Run Error" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;AIUtil(&quot;down_triangle&quot;, micAnyText, micFromTop, 1)&quot;.<BR/><BR/>Line (146): &quot;AIUtil( _&quot;. ]]></Details>
<Time><![CDATA[12-06-2026 - 09:30:48]]></Time>
<TimeTick>1781236848</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" status="Failed" Source="Action1" SourceLine="145" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12-06-2026 - 09:32:23]]></Time>
<TimeTick>1781236943</TimeTick>
<NodeArgs eType="General" icon="8" nRep="24" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12-06-2026 - 09:29:27" eTime="12-06-2026 - 09:32:23" passed="0" failed="3" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[POS_PatchValidation Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12-06-2026 - 09:29:22" eTime="12-06-2026 - 09:32:23" passed="0" failed="3" warnings="5" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test POS_PatchValidation Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>