<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText UFT One" productVer="24.2" os="Windows 11" host="IBM-68H9R24"><DocLocation><![CDATA[C:\Users\BanuchandhiranM\Downloads\POSRegression_Latest (2)\POS_FilePathValidation]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText UFT One"  >
<DName><![CDATA[POS_FilePathValidation]]></DName>
<Res><![CDATA[Res28]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
UIA.]]></Details>
<Time><![CDATA[16-06-2026 - 06:05:54]]></Time>
<TimeTick>1781570154</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[AIUtil.SetContext]]></Obj>
<Details plainTxt="False" ><![CDATA[Set context Window("[ IBM Endpoint Manager for Remote Control ]") for AIUtil]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:11]]></Time>
<TimeTick>1781570171</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="9" nType="AIUtil" Source="Action1" SourceLine="36" >
<Disp><![CDATA[AIUtil.SetContext]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[Login Loaded]]></Obj>
<Details ><![CDATA[US90L01-09956]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:14]]></Time>
<TimeTick>1781570174</TimeTick>
<NodeArgs eType="User" icon="5" nRep="10" Source="Action1" SourceLine="95" >
<Disp><![CDATA[Login Loaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:19]]></Time>
<TimeTick>1781570179</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="105" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf98.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:23]]></Time>
<TimeTick>1781570183</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="109" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf99.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[AIUtil("text_box", "Address").RightClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:24]]></Time>
<TimeTick>1781570184</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="Action1" SourceLine="111" >
<Disp><![CDATA[AIUtil("text_box", "Address").RightClick]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf100.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[AIUtil("text_box", "Address").Type]]></Obj>
<Details plainTxt="False" ><![CDATA["US90L01-09956"]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:31]]></Time>
<TimeTick>1781570191</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="18" Source="Action1" SourceLine="121" >
<Disp><![CDATA[AIUtil("text_box", "Address").Type]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf101.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Lane Address]]></Obj>
<Details ><![CDATA[US90L01-09956]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:31]]></Time>
<TimeTick>1781570191</TimeTick>
<NodeArgs eType="User" icon="5" nRep="19" Source="Action1" SourceLine="123" >
<Disp><![CDATA[Lane Address]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Active")]]></Obj>
<Details plainTxt="False" ><![CDATA[Verifying object identification failed. The object was no longer identified when performing the operation. 
The step was performed but might not have the expected results.]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:38]]></Time>
<TimeTick>1781570198</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" status="Warning" Source="Action1" SourceLine="125" >
<Disp><![CDATA[AIUtil("button", "Active")]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf102.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Active").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:38]]></Time>
<TimeTick>1781570198</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" Source="Action1" SourceLine="125" >
<Disp><![CDATA[AIUtil("button", "Active").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf103.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[AIUtil("combobox", "User ID").Type]]></Obj>
<Details plainTxt="False" ><![CDATA["vn44q8d"]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:47]]></Time>
<TimeTick>1781570207</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Action1" SourceLine="137" >
<Disp><![CDATA[AIUtil("combobox", "User ID").Type]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf104.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[AIUtil("text_box", "Password").Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Chi@1998"]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:49]]></Time>
<TimeTick>1781570209</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" Source="Action1" SourceLine="139" >
<Disp><![CDATA[AIUtil("text_box", "Password").Type]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf105.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[AIUtil("combobox", "Domain").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:51]]></Time>
<TimeTick>1781570211</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" Source="Action1" SourceLine="141" >
<Disp><![CDATA[AIUtil("combobox", "Domain").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf106.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[AIUtil("combobox", "Domain").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:06:56]]></Time>
<TimeTick>1781570216</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" Source="Action1" SourceLine="149" >
<Disp><![CDATA[AIUtil("combobox", "Domain").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf107.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Login")]]></Obj>
<Details plainTxt="False" ><![CDATA[Verifying object identification failed. The object was no longer identified when performing the operation. 
The step was performed but might not have the expected results.]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:06]]></Time>
<TimeTick>1781570226</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" status="Warning" Source="Action1" SourceLine="153" >
<Disp><![CDATA[AIUtil("button", "Login")]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf108.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Login").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:07]]></Time>
<TimeTick>1781570227</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" Source="Action1" SourceLine="153" >
<Disp><![CDATA[AIUtil("button", "Login").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf109.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Total Active Files to Test]]></Obj>
<Details ><![CDATA[1]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:14]]></Time>
<TimeTick>1781570234</TimeTick>
<NodeArgs eType="User" icon="5" nRep="34" Source="Action1" SourceLine="187" >
<Disp><![CDATA[Total Active Files to Test]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:14]]></Time>
<TimeTick>1781570234</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" Source="Action1" SourceLine="194" >
<Disp><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Activate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf110.xml]]></Path>
<ASHilite><![CDATA[1706092]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[332, 10]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:17]]></Time>
<TimeTick>1781570237</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="Action1" SourceLine="198" >
<Disp><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf111.xml]]></Path>
<ASHilite><![CDATA[1706092]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Task Manager").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:29]]></Time>
<TimeTick>1781570249</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" Source="Action1" SourceLine="214" >
<Disp><![CDATA[AIUtil.FindTextBlock("Task Manager").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf112.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("File").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:34]]></Time>
<TimeTick>1781570254</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" Source="Action1" SourceLine="218" >
<Disp><![CDATA[AIUtil.FindTextBlock("File").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf113.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Checking File]]></Obj>
<Details ><![CDATA[Certstorage]]></Details>
<Time><![CDATA[16-06-2026 - 06:07:41]]></Time>
<TimeTick>1781570261</TimeTick>
<NodeArgs eType="User" icon="5" nRep="43" Source="Action1" SourceLine="239" >
<Disp><![CDATA[Checking File]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[FILE FOUND]]></Obj>
<Details ><![CDATA[Certstorage]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:04]]></Time>
<TimeTick>1781570284</TimeTick>
<NodeArgs eType="User" icon="5" nRep="44" Source="Action1" SourceLine="303" >
<Disp><![CDATA[FILE FOUND]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Excel Updated]]></Obj>
<Details ><![CDATA[Result written successfully]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:06]]></Time>
<TimeTick>1781570286</TimeTick>
<NodeArgs eType="User" icon="5" nRep="45" Source="Action1" SourceLine="324" >
<Disp><![CDATA[Excel Updated]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[AIUtil("close", micAnyText, micFromTop, 2).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:07]]></Time>
<TimeTick>1781570287</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" Source="Action1" SourceLine="329" >
<Disp><![CDATA[AIUtil("close", micAnyText, micFromTop, 2).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf114.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:08]]></Time>
<TimeTick>1781570288</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" Source="Action1" SourceLine="340" >
<Disp><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Activate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf115.xml]]></Path>
<ASHilite><![CDATA[1706092]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[AIUtil("close", micAnyText, micFromBottom, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:12]]></Time>
<TimeTick>1781570292</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="Action1" SourceLine="343" >
<Disp><![CDATA[AIUtil("close", micAnyText, micFromBottom, 1).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf116.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[AIUtil("close").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:15]]></Time>
<TimeTick>1781570295</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" Source="Action1" SourceLine="346" >
<Disp><![CDATA[AIUtil("close").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf117.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Yes")]]></Obj>
<Details plainTxt="False" ><![CDATA[Verifying object identification failed. The object was no longer identified when performing the operation. 
The step was performed but might not have the expected results.]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:29]]></Time>
<TimeTick>1781570309</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" status="Warning" Source="Action1" SourceLine="348" >
<Disp><![CDATA[AIUtil("button", "Yes")]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf118.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Yes").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:30]]></Time>
<TimeTick>1781570310</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="Action1" SourceLine="348" >
<Disp><![CDATA[AIUtil("button", "Yes").Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Window ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[16-06-2026 - 06:08:35]]></Time>
<TimeTick>1781570315</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" Source="Action1" SourceLine="351" >
<Disp><![CDATA[[ Window ].Exist]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[Act1\Row0]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="16-06-2026 - 06:05:54" eTime="16-06-2026 - 06:08:39" passed="0" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Warning" >
<Disp><![CDATA[POS_FilePathValidation Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="16-06-2026 - 06:05:52" eTime="16-06-2026 - 06:08:39" passed="0" failed="0" warnings="4" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test POS_FilePathValidation Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>