<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText UFT One" productVer="24.2" os="Windows 11" host="IBM-68H9R24"><DocLocation><![CDATA[C:\Users\BanuchandhiranM\Downloads\POSRegression_Latest (2)\POS_PatchValidation]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText UFT One"  >
<DName><![CDATA[POS_PatchValidation]]></DName>
<Res><![CDATA[Res20]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj ><![CDATA[LoginData]]></Obj>
<Details ><![CDATA[Lane: US90L01-09956 | User: vn44q8d | Domain: Delhaize]]></Details>
<Time><![CDATA[16-06-2026 - 03:01:43]]></Time>
<TimeTick>1781559103</TimeTick>
<NodeArgs eType="User" icon="5" nRep="8" Source="Action1" SourceLine="68" >
<Disp><![CDATA[LoginData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[AIUtil.SetContext]]></Obj>
<Details plainTxt="False" ><![CDATA[Set context Window("[ IBM Endpoint Manager for Remote Control ]") for AIUtil]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:07]]></Time>
<TimeTick>1781559127</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="9" nType="AIUtil" Source="Action1" SourceLine="22" >
<Disp><![CDATA[AIUtil.SetContext]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:08]]></Time>
<TimeTick>1781559128</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="Action1" SourceLine="79" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf178.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:13]]></Time>
<TimeTick>1781559133</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Action1" SourceLine="81" >
<Disp><![CDATA[AIUtil("down_triangle", micAnyText, micFromTop, 1).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf179.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[AIUtil("text_box", "Address").RightClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:14]]></Time>
<TimeTick>1781559134</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="83" >
<Disp><![CDATA[AIUtil("text_box", "Address").RightClick]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf180.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[AIUtil("text_box", "Address").Type]]></Obj>
<Details plainTxt="False" ><![CDATA["US90L01-09956"]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:21]]></Time>
<TimeTick>1781559141</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="90" >
<Disp><![CDATA[AIUtil("text_box", "Address").Type]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf181.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Active")]]></Obj>
<Details plainTxt="False" ><![CDATA[Verifying object identification failed. The object was no longer identified when performing the operation. 
The step was performed but might not have the expected results.]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:35]]></Time>
<TimeTick>1781559155</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="18" status="Warning" Source="Action1" SourceLine="91" >
<Disp><![CDATA[AIUtil("button", "Active")]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf182.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Active").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:36]]></Time>
<TimeTick>1781559156</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="Action1" SourceLine="91" >
<Disp><![CDATA[AIUtil("button", "Active").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf183.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Connection]]></Obj>
<Details ><![CDATA[Connected to lane: US90L01-09956]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:41]]></Time>
<TimeTick>1781559161</TimeTick>
<NodeArgs eType="User" icon="5" nRep="21" Source="Action1" SourceLine="94" >
<Disp><![CDATA[Connection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[AIUtil("combobox", "User ID").Type]]></Obj>
<Details plainTxt="False" ><![CDATA["vn44q8d"]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:48]]></Time>
<TimeTick>1781559168</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" Source="Action1" SourceLine="104" >
<Disp><![CDATA[AIUtil("combobox", "User ID").Type]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf184.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[AIUtil("text_box", "Password").Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Chi@1998"]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:50]]></Time>
<TimeTick>1781559170</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" Source="Action1" SourceLine="105" >
<Disp><![CDATA[AIUtil("text_box", "Password").Type]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf185.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[AIUtil("combobox", "Domain").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:52]]></Time>
<TimeTick>1781559172</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Action1" SourceLine="106" >
<Disp><![CDATA[AIUtil("combobox", "Domain").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf186.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[AIUtil("combobox", "Domain").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:02:57]]></Time>
<TimeTick>1781559177</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" Source="Action1" SourceLine="111" >
<Disp><![CDATA[AIUtil("combobox", "Domain").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf187.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[AIUtil("button", "Login").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:03:04]]></Time>
<TimeTick>1781559184</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="Action1" SourceLine="115" >
<Disp><![CDATA[AIUtil("button", "Login").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf188.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Logged in: vn44q8d]]></Details>
<Time><![CDATA[16-06-2026 - 03:03:12]]></Time>
<TimeTick>1781559192</TimeTick>
<NodeArgs eType="User" icon="5" nRep="32" Source="Action1" SourceLine="118" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:03:12]]></Time>
<TimeTick>1781559192</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="Action1" SourceLine="129" >
<Disp><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Activate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf189.xml]]></Path>
<ASHilite><![CDATA[1906198]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[332, 10]]></Details>
<Time><![CDATA[16-06-2026 - 03:03:15]]></Time>
<TimeTick>1781559195</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" Source="Action1" SourceLine="131" >
<Disp><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf190.xml]]></Path>
<ASHilite><![CDATA[1906198]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Task Manager").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:03:31]]></Time>
<TimeTick>1781559211</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Action1" SourceLine="143" >
<Disp><![CDATA[AIUtil.FindTextBlock("Task Manager").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf191.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("File").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16-06-2026 - 03:03:37]]></Time>
<TimeTick>1781559217</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" Source="Action1" SourceLine="145" >
<Disp><![CDATA[AIUtil.FindTextBlock("File").Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf192.xml]]></Path>
<ASHilite><![CDATA[-1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[PowerShell]]></Obj>
<Details ><![CDATA[Get-HotFix executed. hotfix_id.txt saved on remote.]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:03]]></Time>
<TimeTick>1781559243</TimeTick>
<NodeArgs eType="User" icon="5" nRep="41" Source="Action1" SourceLine="165" >
<Disp><![CDATA[PowerShell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Notepad]]></Obj>
<Details ><![CDATA[hotfix.txt opened in Notepad on remote.]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:09]]></Time>
<TimeTick>1781559249</TimeTick>
<NodeArgs eType="User" icon="5" nRep="42" Source="Action1" SourceLine="172" >
<Disp><![CDATA[Notepad]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Screenshot Captured]]></Obj>
<Details ><![CDATA[Notepad with HotFixIDs captured to: C:\Temp\HotFix_Notepad_Screenshot.png]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:12]]></Time>
<TimeTick>1781559252</TimeTick>
<NodeArgs eType="User" icon="5" nRep="43" Source="Action1" SourceLine="192" >
<Disp><![CDATA[Screenshot Captured]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[HotFix Notepad View]]></Obj>
<Details ><![CDATA[<img src='C:\Temp\HotFix_Notepad_Screenshot.png' width='800'/>]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:12]]></Time>
<TimeTick>1781559252</TimeTick>
<NodeArgs eType="User" icon="5" nRep="44" Source="Action1" SourceLine="196" >
<Disp><![CDATA[HotFix Notepad View]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[400, 300]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:12]]></Time>
<TimeTick>1781559252</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" Source="Action1" SourceLine="207" >
<Disp><![CDATA[[ IBM Endpoint Manager for Remote Control  (US90L01-09956)  ].Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf193.xml]]></Path>
<ASHilite><![CDATA[1906198]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[IBM Endpoint Manager for Remote Control  (US90L01-09956)]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:23]]></Time>
<TimeTick>1781559263</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[IBM Endpoint Manager for Remote Control  (US90L01-09956).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[527, 11]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:23]]></Time>
<TimeTick>1781559263</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" Source="Action1" SourceLine="219" >
<Disp><![CDATA[IBM Endpoint Manager for Remote Control  (US90L01-09956).Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf195.xml]]></Path>
<ASHilite><![CDATA[1906198]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="48" Source="Action1" SourceLine="219" >
<Disp><![CDATA[IBM Endpoint Manager for Remote Control  (US90L01-09956)]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf194.xml]]></Path>
<ASHilite><![CDATA[1906198]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Clipboard Pull]]></Obj>
<Details ><![CDATA[Remote clipboard pulled to local machine.]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:41]]></Time>
<TimeTick>1781559281</TimeTick>
<NodeArgs eType="User" icon="5" nRep="50" Source="Action1" SourceLine="230" >
<Disp><![CDATA[Clipboard Pull]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[Clipboard Saved]]></Obj>
<Details ><![CDATA[HotFix list saved to C:\Temp\hotfix_local.txt]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:42]]></Time>
<TimeTick>1781559282</TimeTick>
<NodeArgs eType="User" icon="5" nRep="51" Source="Action1" SourceLine="257" >
<Disp><![CDATA[Clipboard Saved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[File Read]]></Obj>
<Details ><![CDATA[hotfix_local.txt loaded successfully.]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:42]]></Time>
<TimeTick>1781559282</TimeTick>
<NodeArgs eType="User" icon="5" nRep="52" Source="Action1" SourceLine="286" >
<Disp><![CDATA[File Read]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Excel Opened]]></Obj>
<Details ><![CDATA[PatchValidation sheet loaded.]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:48]]></Time>
<TimeTick>1781559288</TimeTick>
<NodeArgs eType="User" icon="5" nRep="53" Source="Action1" SourceLine="305" >
<Disp><![CDATA[Excel Opened]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[Row Count]]></Obj>
<Details ><![CDATA[Total data rows found: 11]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:50]]></Time>
<TimeTick>1781559290</TimeTick>
<NodeArgs eType="User" icon="5" nRep="54" Source="Action1" SourceLine="316" >
<Disp><![CDATA[Row Count]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[PASS | KB5065755]]></Obj>
<Details ><![CDATA[HotFix KB5065755 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:50]]></Time>
<TimeTick>1781559290</TimeTick>
<NodeArgs eType="User" icon="5" nRep="55" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB5065755]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[PASS | KB4486153]]></Obj>
<Details ><![CDATA[HotFix KB4486153 found on lane. InstalledOn: 12-11-2025 19:00:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:51]]></Time>
<TimeTick>1781559291</TimeTick>
<NodeArgs eType="User" icon="5" nRep="56" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4486153]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[PASS | KB4503308]]></Obj>
<Details ><![CDATA[HotFix KB4503308 found on lane. InstalledOn: 9/16/2019 20:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:51]]></Time>
<TimeTick>1781559291</TimeTick>
<NodeArgs eType="User" icon="5" nRep="57" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4503308]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[PASS | KB4509095]]></Obj>
<Details ><![CDATA[HotFix KB4509095 found on lane. InstalledOn: 9/16/2019 20:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:52]]></Time>
<TimeTick>1781559292</TimeTick>
<NodeArgs eType="User" icon="5" nRep="58" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4509095]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[PASS | KB4512937]]></Obj>
<Details ><![CDATA[HotFix KB4512937 found on lane. InstalledOn: 9/16/2019 20:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:53]]></Time>
<TimeTick>1781559293</TimeTick>
<NodeArgs eType="User" icon="5" nRep="59" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4512937]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[PASS | KB4577586]]></Obj>
<Details ><![CDATA[HotFix KB4577586 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:53]]></Time>
<TimeTick>1781559293</TimeTick>
<NodeArgs eType="User" icon="5" nRep="60" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4577586]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[PASS | KB4589208]]></Obj>
<Details ><![CDATA[HotFix KB4589208 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:54]]></Time>
<TimeTick>1781559294</TimeTick>
<NodeArgs eType="User" icon="5" nRep="61" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4589208]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[PASS | KB4601393]]></Obj>
<Details ><![CDATA[HotFix KB4601393 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:55]]></Time>
<TimeTick>1781559295</TimeTick>
<NodeArgs eType="User" icon="5" nRep="62" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB4601393]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[PASS | KB5005112]]></Obj>
<Details ><![CDATA[HotFix KB5005112 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:55]]></Time>
<TimeTick>1781559295</TimeTick>
<NodeArgs eType="User" icon="5" nRep="63" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB5005112]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[PASS | KB5071544]]></Obj>
<Details ><![CDATA[HotFix KB5071544 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:56]]></Time>
<TimeTick>1781559296</TimeTick>
<NodeArgs eType="User" icon="5" nRep="64" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB5071544]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[PASS | KB5070248]]></Obj>
<Details ><![CDATA[HotFix KB5070248 found on lane. InstalledOn: 12/11/2025 19:00]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:56]]></Time>
<TimeTick>1781559296</TimeTick>
<NodeArgs eType="User" icon="5" nRep="65" status="Passed" Source="Action1" SourceLine="333" >
<Disp><![CDATA[PASS | KB5070248]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Excel Saved]]></Obj>
<Details ><![CDATA[Results written to PatchValidation sheet successfully.]]></Details>
<Time><![CDATA[16-06-2026 - 03:04:57]]></Time>
<TimeTick>1781559297</TimeTick>
<NodeArgs eType="User" icon="5" nRep="66" Source="Action1" SourceLine="367" >
<Disp><![CDATA[Excel Saved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Patch Validation Complete]]></Obj>
<Details ><![CDATA[HotFix validation done. PASS/FAIL written to Column C of PatchValidation sheet.]]></Details>
<Time><![CDATA[16-06-2026 - 03:05:00]]></Time>
<TimeTick>1781559300</TimeTick>
<NodeArgs eType="User" icon="5" nRep="67" Source="Action1" SourceLine="382" >
<Disp><![CDATA[Patch Validation Complete]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Cleanup]]></Obj>
<Details ><![CDATA[Notepad, PowerShell, Task Manager and TRC Console closed.]]></Details>
<Time><![CDATA[16-06-2026 - 03:05:15]]></Time>
<TimeTick>1781559315</TimeTick>
<NodeArgs eType="User" icon="5" nRep="68" Source="Action1" SourceLine="411" >
<Disp><![CDATA[Cleanup]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="16-06-2026 - 03:01:38" eTime="16-06-2026 - 03:05:15" passed="11" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[POS_PatchValidation Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="16-06-2026 - 03:01:33" eTime="16-06-2026 - 03:05:16" passed="11" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test POS_PatchValidation Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>